<?php
/**
 * @file
 * Provides a common interface for communicating with social networking services.
 */

use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme()
 */
function social_api_theme() {
  return array(
    'local_task_list' => array(
      'variables' => array('items' => NULL),
    ),
    'login_with' => array(
      'variables' => array('social_networks' => NULL)
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function social_api_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
 $form['social_api_auth'] = array(
   '#theme' => 'login_with',
   '#weight' => 100,
 );
}

/**
 * Implements hook_preprocess_HOOK()
 */
function social_api_preprocess_login_with(&$variables) {
  $variables['social_networks'] = \Drupal::config('social_api.settings')->get('auth');
}
